version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run cy:parallel
  post_build:
    commands:
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
      - aws s3 sync allure-report s3://reporte-pruebas/
      - aws s3 cp --recursive --acl public-read s3://reporte-pruebas/ s3://reporte-pruebas/ --metadata-directive REPLACE
      - echo "The HTML report can be found here <https://reporte-pruebas.s3.us-east-2.amazonaws.com/index.html>"